alias: "Гараж: управление отоплением"
description: ""
trigger:
  - platform: state
    entity_id:
      - climate.garazh_obshchii
    attribute: temperature
condition: []
action:
  - service: climate.set_temperature
    data:
      temperature: "{{ state_attr('climate.garazh_obshchii','temperature') }}"
    target:
      entity_id:
        - climate.termostat_garazh_1
        - climate.termostat_garazh_2
  - if:
      - condition: state
        entity_id: climate.garazh_obshchii
        state: heating
        attribute: hvac_action
    then:
      - service: climate.set_temperature
        data:
          temperature: "{{ state_attr('climate.garazh_obshchii','temperature') + 3 }}"
        target:
          entity_id:
            - climate.termostat_garazh_1
            - climate.termostat_garazh_2
  - if:
      - condition: state
        entity_id: climate.garazh_obshchii
        attribute: hvac_action
        state: idle
    then:
      - service: climate.set_temperature
        data:
          temperature: "{{ state_attr('climate.garazh_obshchii','temperature') }}"
        target:
          entity_id:
            - climate.termostat_garazh_1
            - climate.termostat_garazh_2
mode: single
